// The code below imports any other important files to configure the app
import '@/setup';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-red-400">Header</header>
        <div className="left-sidebar bg-amber-300 rounded-lg">Your library</div>
        {children}
        <div className="right-sidebar bg-purple-700 rounded-lg">Right sidebar</div>
        <footer className="bg-green-800">Footer</footer>
      </body>
    </html>
  );
}
