// The code below imports any other important files to configure the app
import '@/setup';
import { Footer } from '@/app/_components/footer';
import { Header } from '@/app/_components/header';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <div className="left-sidebar bg-amber-300 rounded-lg hidden lg:flex">Your library</div>
        {children}
        <div className="right-sidebar bg-purple-700 rounded-lg hidden">Right sidebar</div>
        <Footer />
      </body>
    </html>
  );
}
